raw_dir: "input/raw"
fastq_dir: "input/fastq"
index_dir: "input/index/ch38ref"
bam_dir: "output/bam"
counts_dir: "output/counts"
project_curls_path: "config/proyects_metadata_curls.csv"
metadata_path: "config/proyects_metadata_samples_fastqs.csv"
genome_fasta: "input/ref/Homo_sapiens.GRCh38.dna.primary_assembly.fa"
gtf: "input/ref/Homo_sapiens.GRCh38.93.gtf"
whitelist: "input/whitelist/737K-august-2016.txt"
output_dir: "output"
ref_dir: "input/ref"
star_threads: 20

project: null
